provider:
  - Effect: "Allow"
    Action:
      - logs:CreateLogGroup
      - logs:CreateLogStream
      - logs:PutLogEvents
    Resource: "*"
  - Effect: "Allow"
    Action:
      - xray:PutTelemetryRecords
      - xray:PutTraceSegments
    Resource: "*"

helloWorld:
  - Effect: "Allow"
    Action:
      - dynamodb:GetItem
    Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/mytable"
